/*
* Generated file
*
* Generated from: yang module name: task-consumer-impl yang module local name: task-consumer-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Oct 28 13:57:25 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.task_consumer.impl;
public class TaskConsumerModuleFactory extends org.opendaylight.controller.config.yang.config.task_consumer.impl.AbstractTaskConsumerModuleFactory {

}
